### ISSUE TITLE
The API should mirror `Vec`, `HashMap`, and `BTreeMap`.

### ISSUE THREAD

**Issue by KSXGitHub** [tylerhawkes/lease#3]
`Vec::new`, `HashMap::new`, and `BTreeMap::new` don't require any parameter and always return empty object, yet `Pool::new` requires 2 parameters.

## Suggestion

1. Rename current `Pool::new` and `Pool::try_new` to `Pool::with_initial_size` and `Pool::try_with_initial_size` respectively.
2. Create `Pool::new` that takes no parameter and only return `Default::default()`.

**Comment by tylerhawkes** [comment]
These should be implemented in https://github.com/tylerhawkes/lease/pull/4
